// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'github-links-copy'
  | 'github-links-empty'
  | 'github-links-error'
  | 'github-links-extracting'
  | 'github-links-refresh'
  | 'github-links-select-item'
  | 'pref-extract-from-pdf'
  | 'pref-help'
  | 'startup-finish';
